name: cisi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - black
  - gdal
  - geopandas
  - shapely>=2
  - rasterio
  - ruff
  - python-igraph
  - pip
  - pip:
      - nismod-snail==0.5.0
